services:
  api:
    container_name: store_api
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    restart: always
    ports:
      - 7500:7500
    networks:
      - store_network
    volumes:
      - ./apps/api/upload:/app/upload
    env_file:
      - ./apps/api/.env

  client:
    container_name: store_client
    build:
      context: ./apps/ui
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - store_network
    env_file:
      - ./apps/ui/.env.production
    depends_on:
      - api

  admin:
    container_name: store_admin
    build:
      context: ./apps/admin
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3005:80
    networks:
      - store_network
    env_file:
      - ./apps/admin/.env
    depends_on:
      - api

networks:
  store_network:
    name: store_network