// import type { Metadata } from "next";
// import localFont from "next/font/local";
// import "./globals.css";

// const geistSans = localFont({
// 	src: "./assets/fonts/GeistVF.woff",
// 	variable: "--font-geist-sans",
// });
// const geistMono = localFont({
// 	src: "./assets/fonts/GeistMonoVF.woff",
// 	variable: "--font-geist-mono",
// });

// export const metadata: Metadata = {
// 	title: "Create Next App",
// 	description: "Generated by create next app",
// };

// export default function RootLayout({
// 	children,
// }: Readonly<{
// 	children: React.ReactNode;
// }>) {
// 	return (
// 		<html lang="en">
// 			<body className={`${geistSans.variable} ${geistMono.variable}`}>
// 				{children}
// 			</body>
// 		</html>
// 	);
// }

import {
	Footer,
	Header,
	MobileSidebar,
	Sidebar,
} from "@/app/[lang]/components/layout";
import { getDictionary } from "@/dictionaries/get-dictionary";
import type { Locale } from "@/shared/configs/i18n-config";
import { DictionaryProvider } from "@/shared/hooks";
import { TextBlocks } from "@/shared/models";
import { getCollections, getTextByName } from "@/shared/service";
import type { Metadata, ResolvingMetadata } from "next";
import { Inter } from "next/font/google";

import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

type Props = Readonly<{
	params: Promise<{ lang: Locale }>;
	children: React.ReactNode;
}>;

export async function generateMetadata(
	{ params }: Props,
	parent: ResolvingMetadata,
): Promise<Metadata> {
	const { lang } = await params;
	const description = await getTextByName(TextBlocks.main_description);
	return {
		title: "Shop",
		description: description.text[lang],
	};
}

export default async function RootLayout({ params, children }: Props) {
	const { lang } = await params;
	const collections = await getCollections();
	const dictionary = await getDictionary(lang);
	const phones = await getTextByName(TextBlocks.phones);
	return (
		<DictionaryProvider dictionary={dictionary}>
			<main
				className="min-h-screen w-full bg-gray-100 text-gray-700 overflow-hidden"
				x-data="layout"
				style={{ minWidth: "360px" }}
			>
				<Header lang={lang} phones={phones} />
				<div className="flex min-h-screen pt-12">
					<Sidebar list={collections} dictionary={dictionary} lang={lang} />
					<MobileSidebar
						list={collections}
						dictionary={dictionary}
						lang={lang}
					/>
					{children}
				</div>
				<Footer dictionary={dictionary} lang={lang} />
			</main>
		</DictionaryProvider>
	);
}
